// Regenerates lib/data/tcgdex/set_index.g.dart from TCGdex.
//
//   dart run tool/gen_set_index.dart
//
// Fetches GET /sets, then GET /sets/{id} for each (sequential, polite) to pick
// up `abbreviation.official`, which the list endpoint omits. ~220 requests,
// run once in a while — never at app runtime.
import 'dart:convert';
import 'dart:io';

const base = 'https://api.tcgdex.net/v2/en';

Future<Map<String, dynamic>?> getJson(HttpClient c, String path) async {
  for (var attempt = 0; attempt < 3; attempt++) {
    try {
      final req = await c.getUrl(Uri.parse('$base$path'));
      final res = await req.close();
      final body = await utf8.decodeStream(res);
      if (res.statusCode == 200 && body.isNotEmpty) {
        return jsonDecode(body) as Map<String, dynamic>;
      }
      stderr.writeln('  $path -> ${res.statusCode} (attempt ${attempt + 1})');
    } catch (e) {
      stderr.writeln('  $path -> $e (attempt ${attempt + 1})');
    }
    await Future<void>.delayed(const Duration(milliseconds: 500));
  }
  return null;
}

String q(String? s) => s == null ? 'null' : "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";

Future<void> main() async {
  final c = HttpClient();
  final req = await c.getUrl(Uri.parse('$base/sets'));
  final list = (jsonDecode(await utf8.decodeStream(await req.close())) as List)
      .cast<Map<String, dynamic>>();
  stderr.writeln('${list.length} sets');

  final rows = <String>[];
  for (final brief in list) {
    final id = brief['id'] as String;
    final full = await getJson(c, '/sets/$id') ?? brief;
    final cc = (full['cardCount'] as Map<String, dynamic>?) ?? {};
    // TCGdex keeps the printed zero padding for some sets (sv04-042, svp-012,
    // swsh9tg-TG01) but not others (swsh3-20). Detect from the card list.
    final cardIds = ((full['cards'] as List?) ?? const [])
        .whereType<Map<String, dynamic>>()
        .map((c) => c['localId'].toString());
    final zeroPadded = cardIds.any((x) => RegExp(r'^[A-Z]*0\d').hasMatch(x));
    rows.add('  SetInfo('
        'id: ${q(id)}, '
        'name: ${q(full['name'] as String?)}, '
        'serie: ${q((full['serie'] as Map<String, dynamic>?)?['name'] as String?)}, '
        'abbreviation: ${q((full['abbreviation'] as Map<String, dynamic>?)?['official'] as String?)}, '
        'official: ${cc['official'] ?? 0}, '
        'total: ${cc['total'] ?? 0}, '
        'releaseDate: ${q(full['releaseDate'] as String?)}, '
        'hasLogo: ${full['logo'] != null}, '
        'hasSymbol: ${full['symbol'] != null}, '
        'zeroPadded: $zeroPadded'
        '),');
    await Future<void>.delayed(const Duration(milliseconds: 150));
  }
  c.close();

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_set_index.dart on ${DateTime.now().toIso8601String().split('T').first}.')
    ..writeln('// Do not edit by hand. Re-run the script to refresh.')
    ..writeln()
    ..writeln("import 'set_info.dart';")
    ..writeln()
    ..writeln('const kSetIndex = <SetInfo>[')
    ..writeAll(rows, '\n')
    ..writeln()
    ..writeln('];');
  File('lib/data/tcgdex/set_index.g.dart').writeAsStringSync(out.toString());
  stderr.writeln('wrote ${rows.length} rows');
}
