// Regenerates the bundled set indexes from TCGdex.
//
//   dart run tool/gen_set_index.dart          # English and Japanese
//   dart run tool/gen_set_index.dart en       # just one
//
// Fetches GET /sets, then GET /sets/{id} for each (sequential, polite) to pick
// up `abbreviation.official`, the release date and the zero-padding, which the
// list endpoint omits. ~400 requests for both languages.
//
// The bundle is only the offline baseline now: the app also checks TCGdex for
// new sets at runtime (see set_index_refresher.dart), so a set released after
// this was last run still resolves. Re-running it just means new installs do
// not have to fetch anything on first launch.
import 'dart:convert';
import 'dart:io';

import 'package:pokescan/data/tcgdex/set_info.dart';

const base = 'https://api.tcgdex.net/v2';

/// Output file and Dart constant name per language.
const targets = {
  'en': ('lib/data/tcgdex/set_index.g.dart', 'kSetIndex'),
  'ja': ('lib/data/tcgdex/set_index_ja.g.dart', 'kSetIndexJa'),
};

/// TCGdex sheds load with 503s (see image_loader.dart); a set detail that
/// still fails after this many tries aborts the run rather than quietly
/// writing a row with no set code or release date.
const maxAttempts = 6;

Future<Object?> getJson(HttpClient c, String url) async {
  for (var attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      final req = await c.getUrl(Uri.parse(url));
      final res = await req.close();
      final body = await utf8.decodeStream(res);
      if (res.statusCode == 200 && body.isNotEmpty) return jsonDecode(body);
      stderr.writeln('  $url -> ${res.statusCode} (attempt ${attempt + 1})');
    } catch (e) {
      stderr.writeln('  $url -> $e (attempt ${attempt + 1})');
    }
    await Future<void>.delayed(Duration(milliseconds: 500 * (attempt + 1)));
  }
  return null;
}

String q(String? s) => s == null ? 'null' : "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

String source(SetInfo s) => '  SetInfo('
    'id: ${q(s.id)}, '
    'name: ${q(s.name)}, '
    "${s.lang == 'en' ? '' : 'lang: ${q(s.lang)}, '}"
    'serie: ${q(s.serie)}, '
    'serieId: ${q(s.serieId)}, '
    'abbreviation: ${q(s.abbreviation)}, '
    'official: ${s.official}, '
    'total: ${s.total}, '
    'releaseDate: ${q(s.releaseDate)}, '
    'hasLogo: ${s.hasLogo}, '
    'hasSymbol: ${s.hasSymbol}, '
    'zeroPadded: ${s.zeroPadded}'
    '),';

Future<void> generate(HttpClient c, String lang) async {
  final (path, constName) = targets[lang]!;
  final list = ((await getJson(c, '$base/$lang/sets')) as List).cast<Map<String, dynamic>>();
  stderr.writeln('$lang: ${list.length} sets');

  final rows = <String>[];
  for (final brief in list) {
    final id = brief['id'] as String;
    final full = (await getJson(c, '$base/$lang/sets/${Uri.encodeComponent(id)}')) as Map<String, dynamic>?;
    if (full == null) {
      // The brief entry has no code, date or padding. Writing it would
      // silently break lookups for a set that used to work, so stop here and
      // leave the existing file alone.
      stderr.writeln('$lang: giving up on $id after $maxAttempts attempts; $path left unchanged');
      exitCode = 1;
      return;
    }
    rows.add(source(SetInfo.fromSetJson(full, lang: lang)));
    await Future<void>.delayed(const Duration(milliseconds: 150));
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_set_index.dart on ${DateTime.now().toIso8601String().split('T').first}.')
    ..writeln('// Do not edit by hand. Re-run the script to refresh.')
    ..writeln()
    ..writeln("import 'set_info.dart';")
    ..writeln()
    ..writeln('const $constName = <SetInfo>[')
    ..writeAll(rows, '\n')
    ..writeln()
    ..writeln('];');
  File(path).writeAsStringSync(out.toString());
  stderr.writeln('$lang: wrote ${rows.length} rows to $path');
}

Future<void> main(List<String> args) async {
  final langs = args.isEmpty ? targets.keys.toList() : args;
  final c = HttpClient();
  for (final lang in langs) {
    await generate(c, lang);
  }
  c.close();
}
